version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: python
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Güvenli bir şekilde ayarlayın
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # İnitialization SQL dosyasını yükle