apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  ports:
    - port: 80  # Service üzerinde yayımlanan port
      targetPort: 5000  # Container içinde uygulamanın dinlediği port
      nodePort: {{ values.nodePort }}  # Node üzerinde erişim sağlanacak port
  selector:
    app: flask-app
