apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.user.secretName }}
                  key: {{ .Values.postgres.user.secretKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.password.secretName }}
                  key: {{ .Values.postgres.password.secretKey }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.db.secretName }}
                  key: {{ .Values.postgres.db.secretKey }}
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.host.secretName }}
                  key: {{ .Values.postgres.host.secretKey }}
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.port.secretName }}
                  key: {{ .Values.redis.port.secretKey }}
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.host.secretName }}
                  key: {{ .Values.redis.host.secretKey }}
          ports:
            - containerPort: 5000
